### ISSUE TITLE
Endpoint Liste aktualisieren

### ISSUE THREAD

**Issue by simonneutert** [simonneutert/papierkram_api_client#40]
POST Endpunkte für die Aktionen:

  - Anlegen
  - Aktualisieren
  - Löschen
  - Archivieren
  - Aktivieren

von:

- [x] Kontaktpersonen (done via #45)
- [x] Unternehmen (done via #44)
- [x] Waren- und Dienstleistungen (done via #47)
- [x] Projekte (done via #46)
